export const ip = 'http://192.168.100.19/';

const Barangays = [
    { label: "Pandacaqui", value: "pandacaqui" },
    { label: "Sta. Cruz", value: "stacruz" },
    { label: "Acli", value: "acli" },
    { label: "Anao", value: "anao" },
    { label: "Balas", value: "balas" },
    { label: "Buenavista", value: "buenavista" },
    { label: "Camuning", value: "camuning" },
    { label: "Cawayan", value: "cawayan" },
    { label: "Concepcion", value: "concepcion" },
    { label: "Culubasa", value: "culubasa" },
    { label: "Divisoria", value: "divisoria" },
    { label: "Piring", value: "piring" },
    { label: "Eden", value: "eden" },
    { label: "Gandus", value: "gandus" },
    { label: "Lagundi", value: "lagundi" },
    { label: "Laput", value: "laput" },
    { label: "Laug", value: "laug" },
    { label: "Masamat", value: "masamat" },
    { label: "Sto.Cristo", value: "stocristo" },
    { label: "Nueva Victoria", value: "nuevavictoria" },
    { label: "Pangatlan", value: "pangatlan" },
    { label: "Panipuan", value: "panipuan" },
    { label: "Parian", value: "parian" },
    { label: "Sabanilla", value: "sabanilla" },
    { label: "San Antonio", value: "sanantonio" },
    { label: "San Carlos", value: "sancarlos" },
    { label: "San Jose Malino", value: "sanjosemalino" },
    { label: "San Jose Matulid", value: "sanjosematulid" },
    { label: "San Juan", value: "sanjuan" },
    { label: "San Lorenzo", value: "sanlorenzo" },
    { label: "San Miguel", value: "sanmiguel" },
    { label: "San Nicolas", value: "sannicolas" },
    { label: "San Pablo", value: "sanpablo" },
    { label: "San Patricio", value: "sanpatricio" },
    { label: "San Rafael", value: "sanrafael" },
    { label: "San Roque", value: "sanroque" },
    { label: "San Vicente", value: "sanvicente" },
    { label: "Sta. Maria", value: "stamaria" },
    { label: "Santo Domingo", value: "santodomingo" },
    { label: "Santo Rosario", value: "santorosario" },
    { label: "Sapang Maisac", value: "sapangmaisac" },
    { label: "Suclaban", value: "suclaban" },
    { label: "Tangle", value: "tangle" },
]



export default Barangays