import { StyleSheet, Text, View } from "react-native";
import React from "react";

const editProfileForms = StyleSheet.create({
  formText1: {
    fontSize: 20,
    alignSelf: "flex-start",
    left: 45,
    top: 20,
    color: "#F7FFE5",
    fontWeight: "bold",
  },

  formText2: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 20,
    color: "#F7FFE5",
    top: 40,
  },
  formText3: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 20,
    bottom: 20,
    color: "#F7FFE5",
    top: 20,
  },
  formText4: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 20,
    color: "#F7FFE5",
  },
  formText5: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 20,
    bottom: 20,
    color: "#F7FFE5",
  },
  formText6: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 20,
    bottom: 40,
    color: "#F7FFE5",
  },
  formText7: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 4205,
    bottom: 80,
    color: "#F7FFE5",
  },
  formText8: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 20,
    bottom: 80,
    color: "#F7FFE5",
  },

  input1: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#F7FFE5",
    alignSelf: "center",
    borderRadius: 15,
    borderColor: "red",
    borderWidth: 2,
  },

  input2: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#F7FFE5",
    alignSelf: "center",
    bottom: 10,
    top: 30,
    borderRadius: 15,
    borderColor: "#1A5D1A",
    borderWidth: 1,
  },
  input3: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#F7FFE5",
    alignSelf: "center",
    bottom: 30,
    borderRadius: 15,
    borderColor: "#1A5D1A",
    borderWidth: 1,
    top: 10,
  },
  input4: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#F7FFE5",
    alignSelf: "center",
    bottom: 10,
    borderRadius: 15,
    borderColor: "#1A5D1A",
    borderWidth: 1,
  },
  input5: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#F7FFE5",
    alignSelf: "center",
    bottom: 30,
    borderRadius: 15,
    borderColor: "#1A5D1A",
    borderWidth: 1,
  },
  input6: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#F7FFE5",
    alignSelf: "center",
    bottom: 50,
    borderRadius: 15,
    borderColor: "#1A5D1A",
    borderWidth: 1,
  },
  input7: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#F7FFE5",
    alignSelf: "center",
    bottom: 70,
    borderRadius: 15,
    borderColor: "#1A5D1A",
    borderWidth: 1,
  },
  input8: {
    height: 35,
    width: 230,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#F7FFE5",
    alignSelf: "center",
    bottom: 90,
    borderRadius: 15,
    borderColor: "#1A5D1A",
    borderWidth: 1,
  },
});

export { editProfileForms };
