import { StyleSheet } from "react-native";

const formStyle = StyleSheet.create({
  formText1: {
    fontSize: 20,
    alignSelf: "flex-start",
    left: 45,
    top: 20,
    color: "#2E3239",
    fontWeight: "bold",
  },

  formText2: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 45,
    color: "#FBFCF8",
    top: 40,
  },
  formText3: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 45,
    bottom: 20,
    color: "#FBFCF8",
    top: 20,
  },
  formText4: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 45,
    color: "#FBFCF8",
  },
  formText5: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 45,
    bottom: 20,
    color: "#FBFCF8",
  },
  formText6: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 45,
    bottom: 40,
    color: "#FBFCF8",
  },
  formText7: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 45,
    bottom: 80,
    color: "#2E3239",
  },
  formText8: {
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-start",
    left: 40,
    bottom: 80,
    color: "#2E3239",
  },

  input1: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#FBFCF8",
    alignSelf: "center",

    borderRadius: 15,
    borderColor: "red",
  },

  input2: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#FBFCF8",
    alignSelf: "center",
    bottom: 10,
    top: 30,
    borderRadius: 15,
    borderColor: "#1A5D1A",
    borderWidth: 1,
  },
  input3: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#FBFCF8",
    alignSelf: "center",
    bottom: 30,
    borderRadius: 15,
    top: 10,
    borderColor: "#1A5D1A",
    borderWidth: 1,
  },
  input4: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#F7FFE5",
    alignSelf: "center",
    bottom: 10,
    borderRadius: 15,
    borderColor: "#1A5D1A",
    borderWidth: 1,
  },
  input5: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#FBFCF8",
    alignSelf: "center",
    bottom: 30,
    borderRadius: 15,
  },
  input6: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#FBFCF8",
    alignSelf: "center",
    bottom: 50,
    borderRadius: 15,
  },
  input7: {
    height: 35,
    width: 220,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#A2B2EE",
    alignSelf: "center",
    bottom: 70,
    borderRadius: 15,
    borderColor: "red",
  },
  input8: {
    height: 35,
    width: 230,
    margin: 12,
    paddingLeft: 15,
    backgroundColor: "#A2B2EE",
    alignSelf: "center",
    bottom: 90,
    borderRadius: 15,
    borderColor: "red",
  },
});

export { formStyle };
